"""Backtest + walk-forward for ORB on real intraday 5m bars.

Walk-forward design (no parameter tuning — defaults from titan/strategies/orb.py):
  - IS  ("in-sample"):    first 70% of available 5m bars (sanity, NOT for tuning)
  - OOS ("out of sample"): last  30% of available 5m bars (the verdict)

PREREQUISITE: real 5m bars in the `ohlcv` table. If only synth bars are present
(date >= 2026-06-15 from the synth feed), this script will run but the results
are meaningless — synth has no breakout structure.

Backfill with:
    python -m titan.data.backfill --symbols RELIANCE,HDFCBANK,ICICIBANK \\
        --timeframe 5m --days 180

KNOWN LIMITATION: the event-loop backtester (titan/backtest/engine.py) currently
only acts on ENTRY_LONG signals. ORB short entries will be ignored. The verdict
below reflects the LONG-only side; a full assessment requires extending the
engine or reporting one-sided results explicitly.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from titan.backtest.engine import load_bars, run_backtest, BTResult
from titan.strategies.orb import OpeningRangeBreakout


SYMBOLS = ["RELIANCE", "HDFCBANK", "ICICIBANK"]
TIMEFRAME = "5m"
SYNTH_BOUNDARY = "2026-06-15"  # bars at/after this date are synth-generated

# Predeclared ship/kill thresholds (intraday breakout, 1.5R target).
THRESHOLDS = [
    ("OOS Sharpe ≥ 0.6",     lambda r: r["sharpe"] >= 0.6,         "{sharpe:.2f}"),
    ("Max DD ≤ 15%",         lambda r: r["max_dd"] <= 15,          "{max_dd:.1f}%"),
    ("Hit rate ≥ 35%",       lambda r: r["hit_rate"] >= 0.35,      "{hit_rate_pct:.1f}%"),
    ("Profit factor ≥ 1.10", lambda r: r["pf"] >= 1.10,            "{pf:.2f}"),
    ("Avg bars held ≥ 1",    lambda r: r["bars_held"] >= 1,        "{bars_held:.1f}"),
]


def fmt(res: BTResult, label: str) -> str:
    return f"\n### {label} — {res.symbol}\n```\n{res.to_markdown()}\n```\n"


def split(bars):
    n = len(bars)
    cut = int(n * 0.70)
    return bars.iloc[:cut], bars.iloc[cut:]


def main():
    out = ["# ORB Backtest Results", "",
           f"_Generated by scripts/run_orb_backtest.py_", "",
           "**LONG-only** — backtest engine does not yet evaluate ENTRY_SHORT signals.", ""]

    aggregate = {"IS": [], "OOS": []}
    synth_only = []

    for sym in SYMBOLS:
        full = load_bars(sym, TIMEFRAME)
        if full.empty:
            out.append(f"_no bars for {sym}_ — backfill required")
            continue

        first_real = full.index[0].date().isoformat()
        all_synth = first_real >= SYNTH_BOUNDARY
        if all_synth:
            synth_only.append(sym)

        out.append(f"## {sym} — {len(full)} {TIMEFRAME} bars "
                   f"({full.index[0]} → {full.index[-1]})"
                   + ("  ⚠️ synth only" if all_synth else ""))

        is_bars, oos_bars = split(full)
        for label, bars in [("In-sample (70%)", is_bars),
                            ("Out-of-sample (30%)", oos_bars)]:
            strat = OpeningRangeBreakout(sym)
            res = run_backtest(strat, bars, starting_equity=50000.0)
            out.append(fmt(res, label))
            key = "IS" if label.startswith("In") else "OOS"
            aggregate[key].append(res)

    # ── aggregate ──
    out.append("## Aggregate (sum across symbols)\n")
    for label, runs in aggregate.items():
        if not runs:
            continue
        n = sum(r.n_trades for r in runs)
        pnl = sum(r.total_pnl for r in runs)
        cst = sum(r.total_costs for r in runs)
        sharpes = [r.sharpe for r in runs if r.n_trades > 0]
        avg_sh = sum(sharpes) / len(sharpes) if sharpes else 0.0
        avg_dd = sum(r.max_dd_pct for r in runs) / len(runs)
        out.append(
            f"- **{label}**: {n} trades · net P&L ₹{pnl:+.2f} · "
            f"costs ₹{cst:.2f} · avg per-symbol Sharpe {avg_sh:.2f} · "
            f"avg max DD {avg_dd:.2f}%"
        )

    # ── verdict ──
    out.append("\n## Verdict (predeclared thresholds)\n")
    oos_runs = [r for r in aggregate["OOS"] if r.n_trades > 0]
    if not oos_runs:
        out.append("⚠️ No OOS trades — cannot evaluate. Backfill real intraday data first.")
    else:
        sharpes = [r.sharpe for r in oos_runs]
        metrics = {
            "sharpe":        sum(sharpes) / len(sharpes),
            "max_dd":        sum(r.max_dd_pct for r in oos_runs) / len(oos_runs),
            "hit_rate":      sum(r.hit_rate for r in oos_runs) / len(oos_runs),
            "hit_rate_pct":  sum(r.hit_rate for r in oos_runs) / len(oos_runs) * 100,
            "pf":            sum(min(r.profit_factor, 10) for r in oos_runs) / len(oos_runs),
            "bars_held":     sum(r.avg_bars_held for r in oos_runs) / len(oos_runs),
        }
        results = []
        for name, check, fmt_str in THRESHOLDS:
            ok = check(metrics)
            results.append(ok)
            out.append(f"- {'✅' if ok else '❌'} {name} — actual "
                       + fmt_str.format(**metrics))
        ship = all(results)
        out.append(f"\n### {'**SHIP** — wire into supervisor for paper rehearsal.' if ship else '**KILL** — does not clear bar; investigate before enabling.'}")

    if synth_only:
        out.append("")
        out.append("⚠️ **Warning:** symbols [" + ", ".join(synth_only)
                   + "] have ONLY synth-generated bars (date ≥ "
                   + SYNTH_BOUNDARY + "). Results are NOT a real-data verdict.")

    txt = "\n".join(out)
    print(txt)
    Path("docs/research").mkdir(parents=True, exist_ok=True)
    Path("docs/research/03_orb_results.md").write_text(txt)


if __name__ == "__main__":
    main()
