"""Backtest + walk-forward for TSMOM on the 2y of daily data we pulled.

Walk-forward design (no parameter tuning — we picked params from literature):
  - IS  ("in-sample"):    full window 2024-06-13 → 2025-12-31  (used to
                          confirm the strategy produces *any* signals on real
                          data; we do NOT tune on it)
  - OOS ("out of sample"): 2026-01-01 → 2026-06-13              (the verdict)

We also report per-symbol results so we can see which equities the
strategy actually has an edge in vs random.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from titan.backtest.engine import load_bars, run_backtest, BTResult
from titan.strategies.tsmom import TSMOM


def fmt(res: BTResult, label: str) -> str:
    return f"\n### {label} — {res.symbol}\n```\n{res.to_markdown()}\n```\n"


def main():
    symbols = ["RELIANCE", "HDFCBANK", "ICICIBANK"]
    out = ["# TSMOM Backtest Results", "", f"_Generated by scripts/run_tsmom_backtest.py_", ""]

    aggregate = {"IS": [], "OOS": []}
    for sym in symbols:
        full = load_bars(sym, "1d")
        if full.empty:
            out.append(f"_no bars for {sym}_")
            continue
        out.append(f"## {sym} — {len(full)} daily bars "
                   f"({full.index[0].date()} → {full.index[-1].date()})")

        is_bars  = full.loc[:"2025-12-31"]
        oos_bars = full.loc["2026-01-01":]

        for label, bars in [("In-sample 2024-06 → 2025-12", is_bars),
                            ("Out-of-sample 2026-01 → 2026-06", oos_bars)]:
            strat = TSMOM(sym)
            res = run_backtest(strat, bars, starting_equity=5000.0)
            out.append(fmt(res, label))
            key = "IS" if label.startswith("In-sample") else "OOS"
            aggregate[key].append(res)

    # ── aggregate verdict ──
    out.append("## Aggregate (sum of net P&L across all 3 symbols)\n")
    for label, runs in aggregate.items():
        if not runs:
            continue
        n   = sum(r.n_trades for r in runs)
        pnl = sum(r.total_pnl for r in runs)
        cst = sum(r.total_costs for r in runs)
        sharpes = [r.sharpe for r in runs if r.n_trades > 0]
        avg_sh  = sum(sharpes) / len(sharpes) if sharpes else 0.0
        avg_dd  = sum(r.max_dd_pct for r in runs) / len(runs)
        out.append(
            f"- **{label}**: {n} trades · net P&L ₹{pnl:+.2f} · "
            f"costs ₹{cst:.2f} · avg per-symbol Sharpe {avg_sh:.2f} · "
            f"avg max DD {avg_dd:.2f}%"
        )

    # ── ship/kill verdict (predeclared thresholds) ──
    out.append("\n## Verdict (predeclared thresholds)\n")
    oos_runs = aggregate["OOS"]
    if oos_runs:
        sharpes = [r.sharpe for r in oos_runs if r.n_trades > 0]
        avg_sh = sum(sharpes) / len(sharpes) if sharpes else 0.0
        avg_dd = sum(r.max_dd_pct for r in oos_runs) / len(oos_runs)
        avg_hit = sum(r.hit_rate for r in oos_runs) / len(oos_runs)
        avg_pf  = sum(min(r.profit_factor, 10) for r in oos_runs) / len(oos_runs)
        avg_held = sum(r.avg_bars_held for r in oos_runs) / len(oos_runs)
        checks = [
            ("OOS Sharpe ≥ 0.4",      avg_sh >= 0.4,  f"{avg_sh:.2f}"),
            ("Max DD ≤ 25%",          avg_dd <= 25,   f"{avg_dd:.1f}%"),
            ("Hit rate ≥ 30%",        avg_hit >= 0.30, f"{avg_hit*100:.1f}%"),
            ("Profit factor ≥ 1.05",  avg_pf >= 1.05,  f"{avg_pf:.2f}"),
            ("Avg bars held ≥ 2",     avg_held >= 2,   f"{avg_held:.1f}"),
        ]
        for name, ok, val in checks:
            out.append(f"- {'✅' if ok else '❌'} {name} — actual {val}")
        ship = all(ok for _, ok, _ in checks)
        out.append(f"\n### {'**SHIP** — wire into supervisor for paper rehearsal.' if ship else '**KILL** — does not clear bar; investigate before enabling.'}")
    txt = "\n".join(out)
    print(txt)
    Path("docs/research/01_tsmom_results.md").write_text(txt)


if __name__ == "__main__":
    main()
